services:
  - type: web
    name: rag-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run rag_excel_app.py --server.port $PORT --server.address 0.0.0.0
    plan: free